spring:
  application:
    name: commodity
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    context-path: /commodity
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  port: 8081

logging:
  config: classpath:logback-spring.xml
